<?php

/**
 * @file
 * field_validation installation file
 */

/**
 * Implements hook_schema().
 */
function field_validation_schema() {
  $schema['field_validation_rule'] = array(
    'description' => 'Stores rule definitions',
    'fields' => array(
      'ruleid' => array(
        'type' => 'serial',
        'description' => 'Unique identifier for a rule',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'rulename' => array(
        'type' => 'varchar',
        'description' => 'Name for the rule',
        'not null' => TRUE,
        'default' => '',
        'length' => 255,
      ),
			'field_name' => array(
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => ''
      ),
			'col' => array(
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => 'value'
      ),			
      'entity_type' => array(
        'type' => 'varchar',
        'length' => 32,
        'not null' => TRUE,
        'default' => ''
      ),
      'bundle' => array(
        'type' => 'varchar',
        'length' => 128,
        'not null' => TRUE,
        'default' => ''
      ),
      'validator' => array(
        'type' => 'varchar',
        'description' => 'The validator key',
        'not null' => TRUE,
        'default' => '',
        'length' => 255,
      ),
      'data' => array(
        'type' => 'varchar',
        'description' => 'Additional rule data',
        'not null' => FALSE,
        'length' => 255,
      ),
      'error_message' => array(
        'type' => 'varchar',
        'description' => 'Rule error message',
        'not null' => FALSE,
        'length' => 255,
      ),
    ),
    'primary key' => array('ruleid'),
    'indexes' => array(
      'field_name_bundle' => array('field_name', 'entity_type', 'bundle'),
    ),
  );

  return $schema;
}

/**
 * add 'col' to schema.
 */
function field_validation_update_7000(&$sandbox) {
	$col = array(
    'type' => 'varchar',
    'length' => 32,
    'not null' => TRUE,
    'default' => 'value'
  );
  db_add_field('field_validation_rule', 'col', $col);
}